/* This file is automatically generated. DO NOT EDIT! */

#ifndef _c2r_h
#define _c2r_h


#include <rsf.h>


void c2r_init(
    sf_axis ax_,
    sf_axis az_,
    sf_axis ag_,
    sf_axis at_,
    bool verb_);
/*< initialize >*/


void c2r(
    bool linear,
    bool adj,
    float      **mapCC,
    float      **mapRC,
    sf_complex **rays );
/*< interpolation switch >*/


void c2r_linear(
    bool      adj,
    float      **mapCC,
    float      **mapRC,
    sf_complex **rays);
/*< linear interpolation >*/


void c2r_sinc(
    bool      adj,
    float      **mapCC,
    float      **mapRC,
    sf_complex **rays);
/*< sinc interpolation >*/

#endif
