/* This file is automatically generated. DO NOT EDIT! */

#ifndef _ctoeplitz_h
#define _ctoeplitz_h


#include <rsf.h>


#include "ctoeplitz.h"


void ctoeplitz_init (int n_in /* matrix size */);
/*< initialize >*/


void ctoeplitz_solve (const sf_complex *r /* top row of the matrix */, 
		      sf_complex *f       /* inverted in place */);
/*< apply the solver >*/


void ctoeplitz_close();
/*< free allocated storage >*/

#endif
