/* This file is automatically generated. DO NOT EDIT! */

#ifndef _dsr_h
#define _dsr_h


void dsr_init (float eps1 /* regularization */, 
	       int nw1    /* number of frequencies */,
	       int nt     /* time samples */, 
	       float dt   /* time sampling */, 
	       int nz1    /* depth samples */, 
	       float dz1  /* depth sampling */, 
	       float *vt1 /* velocity/slowness */, 
	       float *vz1 /* vertical velocity/slowness */,
	       float *eta1 /* eta */,
	       bool depth /* depth or time migration */,
	       char rule   /* interpolation rule */,
	       int na1     /* angle samples */,
	       float da1   /* angle sampling */);
/*< initialize >*/


void dsr_close ();
/*< free workspace >*/


void dsr (char rule /* rule for angle gathers */,
	  bool inv /* modeling or migration */, 
	  float kx /* midpoint wavenumber */, 
	  float kh /* half-offset wavenumber */, 
	  float *p /* time trace */, 
	  float **q /* angle gathers */);
/*< apply >*/

#endif
