/* This file is automatically generated. DO NOT EDIT! */

#ifndef _extend_h
#define _extend_h


void extend1 (int ne     /* padding */, 
	     int nd     /* data length */, 
	     float *dat /* data [nd] */, 
	     float *ext /* extension [nd+2*ne] */);
/*< 1-D extension >*/


void extend2 (int ne         /* padding */, 
	      int n1, int n2 /* data size */, 
	      float** dat    /* data [n2][n1] */, 
	      float** ext    /* extension [n2+2*ne][n1+2*ne] */, 
	      float* tmp1    /* temporary storage [n2] */, 
	      float* tmp2    /* temporary storage [n2+2*ne] */);
/*< 2-D extension >*/

#endif
