/* This file is automatically generated. DO NOT EDIT! */

#ifndef _fdmig_h
#define _fdmig_h


#include <rsf.h>


void fdmig_init(bool hi1    /* if use 45-degree */, 
		int nx1     /* lateral samples */, 
		int nz1     /* vertical samples */, 
		int nw1     /* frequency samples */, 
		float dx    /* lateral sampling */, 
		float dz    /* vertical sampling */, 
		float dw1   /* frequency sampling */, 
		float vel   /* velocity */, 
		float beta1 /* "one-sixth" term */);
/*< Initialize >*/


void fdmig_close(void);
/*< Free allocated storage >*/


void fdmig (sf_complex **dat /* input data */, 
	    float **img         /* output image */, 
	    sf_file movie       /* save movie (if not NULL) */);
/*< Migrate >*/

#endif
