/* This file is automatically generated. DO NOT EDIT! */

#ifndef _fft2_h
#define _fft2_h


#include <rsf.h>


/*------------------------------------------------------------*/
void fft2_init(int n1_, int n2_);
/*< initialize >*/


/*------------------------------------------------------------*/
void fft2_close(void);
/*< Free allocated storage >*/


/*------------------------------------------------------------*/
void fft2(bool inv          /* inverse/forward flag */, 
	  kiss_fft_cpx **pp /* [1...n2][1...n1] */);
/*< Apply 2-D FFT >*/


/*------------------------------------------------------------*/
void sft2_init(float o1, float d1, 
	       float o2, float d2);
/*< origin shift (assumes no centering) >*/


/*------------------------------------------------------------*/
void sft2_close();
/*< close shift >*/


/*------------------------------------------------------------*/
void sft2(sf_complex **pp);
/*< apply shift >*/


/*------------------------------------------------------------*/
void cnt2(sf_complex **pp);
/*< apply centering >*/

#endif
