/* This file is automatically generated. DO NOT EDIT! */

#ifndef _freqlet_h
#define _freqlet_h


void freqlet_init(int n /* data size */, bool inv1, bool unit1, char type);
/*< allocate space >*/


void freqlet_set(float w0);
/*< set frequency >*/


void freqlet_setz(sf_complex z0);
/*< set z=exp(i*w) >*/


void freqlet_close(void);
/*< deallocate space >*/


void freqlet_lop(bool adj, bool add, int nx, int ny, 
		 sf_complex *x, sf_complex *y);
/*< linear operator >*/

#endif
