/* This file is automatically generated. DO NOT EDIT! */

#ifndef _freqlets_h
#define _freqlets_h


 
void freqlets_init(int n1 /* data size */, 
		   float d1 /* sampling */,
		   bool inv, bool unit, char type,
		   int nw1 /* number of frequencies */, 
		   float *w1      /* [nw] frequencies */,
		   sf_complex *z1 /* [nw] Z factors */);
/*< allocate space >*/


void freqlets_close(void);
/*< deallocate space >*/


void freqlets_set(float *w1, sf_complex *z1);
/*< set frequency >*/


void freqlets_lop(bool adj, bool add, int nx, int ny, 
		  sf_complex *x, sf_complex *y);
/*< linear operator >*/

#endif
