/* This file is automatically generated. DO NOT EDIT! */

#ifndef _gazdag_h
#define _gazdag_h


#include <rsf.h>


void gazdag_init (float eps1  /* regularization */, 
		  int nt      /* time samples */, 
		  float dt    /* time sampling */, 
                  int nz1     /* depth samples */, 
		  float dz1   /* depth sampling */, 
		  float *vt1  /* velocity (time) or slowness (depth) */, 
		  float *vz1,
		  float *eta1,
		  bool depth  /* depth (or time) */,
		  char rule   /* interpolation rule */);
/*< Initialize >*/


void gazdag_close ();
/*< Free allocated storage >*/


void gazdag (bool inv  /* modeling (or migration) */,
	     float k2  /* wavenumber squared */, 
	     float *p  /* data [nt] */, 
	     float *q  /* image [nz] */);
/*< Run >*/

#endif
