/* This file is automatically generated. DO NOT EDIT! */

#ifndef _img2_h
#define _img2_h


#include <rsf.h>


/*------------------------------------------------------------*/
void img2dec(int dec1, float eps1);
/*< set deconvolution count >*/


/*------------------------------------------------------------*/
void img2store( int imz,
		sf_complex **ww_s,
		sf_complex **ww_r
    );
/*< store wavefield >*/


/*------------------------------------------------------------*/
void img2o_init(sf_axis amx_,
		sf_axis amy_,
		sf_axis amz_,
		int jcx_,
		int jcy_,
		int jcz_,
		sf_fslice imag
    );
/*< initialize zero-lag I.C. >*/


void img2x_init(sf_axis amx_,
		sf_axis amy_,
		sf_axis amz_,
		int jcx_,
		int jcy_,
		int jcz_,
		sf_axis ahx_,
		sf_axis ahy_,
		sf_axis ahz_,
		sf_fslice imag
    );
/*< initialize x-lag I.C. >*/


void img2t_init(sf_axis amx_,
		sf_axis amy_,
		sf_axis amz_,
		int jcx_,
		int jcy_,
		int jcz_,
		sf_axis aht_,
		sf_axis aw_,
		sf_fslice imag
    );
/*< initialize t-lag I.C. >*/


void img2h_init(sf_axis amx_,
		sf_axis amy_,
		sf_axis amz_,
		int jcx_,
		int jcy_,
		int jcz_,
		sf_axis ahh_,
		sf_axis aha_,
		sf_axis ahb_,
		sf_axis aw_,
		sf_fslice imag,
		float vpvs_
    );
/*< initialize abs x-lag I.C. >*/


/*------------------------------------------------------------*/
void img2o(int iw);
/*< apply zero-lag I.C. >*/


/*------------------------------------------------------------*/
void img2x(int iw);
/*< apply x-lag I.C. >*/


/*------------------------------------------------------------*/
void img2t(int iw);
/*< apply t-lag I.C. >*/


/*------------------------------------------------------------*/
void img2h(int iw);
/*< apply abs x-lag I.C. >*/


/*------------------------------------------------------------*/
void img2g(int iw);
/*< apply abs x-lag I.C. >*/


/*------------------------------------------------------------*/
void img2o_close(sf_fslice imag,
		 sf_fslice cigs);
/*< deallocate zero-lag I.C. >*/


/*------------------------------------------------------------*/
void img2t_close(sf_fslice imag,
		 sf_fslice cigs);
/*< deallocate t-lag I.C. >*/


/*------------------------------------------------------------*/
void img2h_close(sf_fslice imag,
		 sf_fslice cigs);
/*< deallocate abs x-lag I.C. >*/


/*------------------------------------------------------------*/
void img2x_close(sf_fslice imag,
		 sf_fslice cigs);
/*< deallocate x-lag I.C. >*/


/*------------------------------------------------------------*/
void img2_close();
/*< deallocate >*/

#endif
