/* This file is automatically generated. DO NOT EDIT! */

#ifndef _invert_h
#define _invert_h


void invert(sf_operator oper /* linear operator */, 
	    int niter        /* number of iterations */,
	    int miter        /* memory */, 
	    int nx, int ny   /* model and data size */,
	    float *x         /* model */, 
	    const float *y   /* data */, 
	    float *error     /* least-squares error */);
/*< Iterative least-squares optimization >*/

#endif
