/* This file is automatically generated. DO NOT EDIT! */

#ifndef _kirmod3_h
#define _kirmod3_h


#include "kirmod.h"


typedef struct Velocity3 {
    float v0, gx, gy, gz, x0, y0, z0, vz, n;
} *velocity3;


void kirmod3_init(float fx1, float dx1,
		  float fy1, float dy1             /* reflector sampling */,
		  velocity3 v1                     /* velocity attributes */,
		  char type1                       /* velocity distribution */,
		  float ***curve1                  /* reflectors */,
		  float ***dipx1                   /* reflector inline dip */,
		  float ***dipy1                   /* reflector cross dip */);
/*< Initialize >*/


void kirmod3_map(ktable ta          /* ray attribute object */,
		 const float *xy    /* surface position */,
		 int ix, int iy     /* point on the surface */,
		 int ic             /* surface number */);
/*< Compute traveltimes and amplitudes >*/

#endif
