/* This file is automatically generated. DO NOT EDIT! */

#ifndef _lsr_h
#define _lsr_h


void lsr_init( sf_axis az_,
	       sf_axis ax_,
	       sf_axis ay_,
	       int px,
	       int py
    );
/*< initialize >*/


void lsr_close(void);
/*< free allocated storage >*/


void kweight( float **bs, /* slowness */
	      float   wo  /* frequency */
);
/*< k-domain weight >*/


/*------------------------------------------------------------*/
void lsr_s2w(
    sf_complex    w /* frequency */,
    sf_complex **bw /* background   wavefield */,
    float      **bs /* background   slowness  */,
    sf_complex **pw /* perturbation wavefield */,
    sf_complex **ps /* perturbation slowness  */
    );
/*< linear scattering operator (forward) >*/


/*------------------------------------------------------------*/
void lsr_w2s(
    sf_complex    w /* frequency */,
    sf_complex **bw /* background   wavefield */,
    float      **bs /* background   slowness  */,
    sf_complex **pw /* perturbation wavefield */,
    sf_complex **ps /* perturbation slowness  */
    );
/*< linear scattering operator (adjoint) >*/

#endif
