/* This file is automatically generated. DO NOT EDIT! */

#ifndef _pshift_h
#define _pshift_h


#include <rsf.h>


void pshift_init(bool depth1 /* depth (or time) */,
				 char rule1 /* interpolation rule */);
/*< Initialize >*/


sf_complex pshift(sf_complex w2, float k2, float v1, float v2, float vz, float n);
/*< phase shift for different rules >*/

#endif
