/* This file is automatically generated. DO NOT EDIT! */

#ifndef _radon_h
#define _radon_h


#include <rsf.h>


void radon_init (int nx_in                            /* number of offsets */, 
		 int np_in , float dp_in, float p0_in /* slope axis */);
/*< initialize >*/


void radon_close ();
/*< free allocated storage >*/


void radon_set (float w   /* frequency */, 
		float* xx /* offset [nx] */);
/*< set the matrix >*/


void radon_toep (sf_complex *qq /* Toeplitz row */, 
		 float eps         /* regularization */);
/*< fill Toeplitz matrix for inversion >*/


void radon_lop (bool adj, bool add, int nm, int nd, 
		sf_complex *mm, sf_complex *dd);
/*< linear operator >*/

#endif
