/* This file is automatically generated. DO NOT EDIT! */

#ifndef _slowref_h
#define _slowref_h


int slowref(int nr           /* maximum number of references */, 
	    float ds         /* minimum slowness separation */, 
	    int ns           /* number of slownesses */, 
	    const float* ss  /* [ns] slowness array */, 
	    float* sr        /* [nr] reference slownesses squared */);
/*< compute reference slownesses, return their number >*/

#endif
