/* This file is automatically generated. DO NOT EDIT! */

#ifndef _srmva_h
#define _srmva_h


#include <rsf.h>


void srmva_init(bool verb_,
		float eps_,
		bool twoway_,
		float dtmax,
		sf_axis aw_      /* frequency */,
		sf_axis amx_     /* i-line (data) */,
		sf_axis amy_     /* x-line (data) */,
		sf_axis amz_     /* depth */,
		sf_axis alx_     /* i-line (slowness/image) */,
		sf_axis aly_     /* x-line (slowness/image) */,
		int tmx, int tmy /* taper size */,
		int pmx, int pmy /* padding in the k domain */,
		int    nrmax,    /* maximum number of references */
		sf_fslice slow_,
		sf_fslice wfls_,
		sf_fslice wflr_
    );
/*< initialize >*/


void srmva_close(void);
/*< free allocated storage >*/


void srmva(bool adj     /* forward/adjoint flag */, 
	   sf_fslice Pslow /* slowness perturbation [nz][nmy][nmx] */,
	   sf_fslice Pimag /*    image perturbation [nz][nmy][nmx] */);
/*< Apply forward/adjoint SR MVA >*/

#endif
