/* This file is automatically generated. DO NOT EDIT! */

#ifndef _ssr_h
#define _ssr_h


#include <rsf.h>


/*------------------------------------------------------------*/
void ssr_init( sf_axis az_,
	       sf_axis ax_,
	       sf_axis ay_,
	       sf_axis lx_,
	       sf_axis ly_,
	       int px,
	       int py,
	       int tx,
	       int ty,
	       float dsmax
    );
/*< initialize >*/


/*------------------------------------------------------------*/
void ssr_close(void);
/*< free allocated storage >*/


/*------------------------------------------------------------*/
void ssr_ssf(
    sf_complex    w /* frequency */,
    sf_complex **wx /* wavefield */,
    float         **so /* slowness  */, 
    float         **ss /* slowness  */,
    int             nr /* nr. of ref slo */,
    float          *sm /* ref slo squared */
    );
/*< Wavefield extrapolation by SSF >*/


/*------------------------------------------------------------*/
void ssr_sso(
    sf_complex    w /* frequency */,
    sf_complex **wx /* wavefield */,
    float      **so /* slowness  */, 
    float      **ss /* slowness  */,
    int          nr /* nr. of ref slo */,
    float       *sm /* ref slo squared */
    );
/*< Wavefield extrapolation by SSF w/ one reference slowness >*/


/*------------------------------------------------------------*/
void ssr_phs(
    sf_complex    w /* frequency */,
    sf_complex **wx /* wavefield */,
    float      **so /* slowness  */, 
    float      **ss /* slowness  */,
    int          nr /* nr. of ref slo */,
    float       *sm /* ref slo squared */
    );
/*< Wavefield extrapolation by phase-shift >*/


/*------------------------------------------------------------*/
void ssr_pho(
    sf_complex    w /* frequency */,
    sf_complex **wx /* wavefield */,
    float      **so /* slowness  */, 
    float      **ss /* slowness  */,
    int          nr /* nr. of ref slo */,
    float       *sm /* ref slo squared */
    );
/*< Wavefield extrapolation by phase-shift w/ one reference >*/

#endif
