/* This file is automatically generated. DO NOT EDIT! */

#ifndef _stretch4_h
#define _stretch4_h


typedef struct Map4 *map4;
/* abstract data type */


map4 stretch4_init (int n1, float o1, float d1 /* regular axis */, 
		    int nd                     /* data samples */, 
		    float eps                  /* regularization */);
/*< initialize >*/


void stretch4_define (map4 str, const float* coord /* [nd] */);
/*< set coordinates >*/


void cstretch4_apply (map4 str, 
		      const sf_complex* ord /* [nd] */, 
		      sf_complex* mod       /* [n1] */);
/*< complex transform ordinates to model >*/


void stretch4_apply (map4 str, 
		     const float* ord /* [nd] */, 
		     float* mod       /* [n1] */);
/*< transform ordinates to model >*/


void cstretch4_invert (map4 str, 
		       sf_complex* ord       /* [nd] */, 
		       const sf_complex* mod /* [n1] */);
/*< convert model to ordinates by spline interpolation >*/


void stretch4_invert (map4 str, 
		      float* ord       /* [nd] */, 
		      const float* mod /* [n1] */);
/*< convert model to ordinates by spline interpolation >*/


void stretch4_close (map4 str);
/*< free allocated storage >*/

#endif
