/* This file is automatically generated. DO NOT EDIT! */

#ifndef _velcon_h
#define _velcon_h


void velcon_init(int nt1   /* time samples */,
		 int nx1   /* space samples */,
		 float dt1 /* time sampling */,
		 float dx1 /* space sampling */,
		 float t1  /* time origin */,
		 int pad1, 
		 int pad2  /* padding in time */,
		 int next /* trace extension */);
/*< initialize >*/


void velcon_close(void);
/*< free allocated storage >*/


void velcon(float ** data /* [nx][nt] */,
	    float v0      /* initial velocity */,
	    float v1      /* new velocity */);
/*< apply velocity continuation >*/

#endif
