/* This file is automatically generated. DO NOT EDIT! */

#ifndef _veltran_h
#define _veltran_h


#include <rsf.h>


void veltran_init (bool pull1                     /* pull or push mode */, 
		   float x01, float dx1, int nx1  /* offset axis */, 
		   float s01, float ds1, int ns1  /* slowness axis */, 
		   float t01, float dt1, int nt1  /* time axis */, 
		   float s11                      /* reference slowness */, 
		   float anti1                    /* antialiasing */, 
		   int psun11, int psun21         /* amplitude case */);
/*< initialize >*/


void veltran_close (void);
/*< free allocated storage >*/


void veltran_lop (bool adj, bool add, int nm, int nd, float *modl, float *data);
/*< linear operator >*/

#endif
