/* This file is automatically generated. DO NOT EDIT! */

#ifndef _vt2w_h
#define _vt2w_h


float vt2w (int nt      /* time axis length */, 
	    float *vt   /* [nt] velocity in time */,
	    float *str  /* [nt] stretch (output) */);
/*< Evaluate Stolt stretch >*/

#endif
