/* This file is automatically generated. DO NOT EDIT! */

#ifndef _warp3_h
#define _warp3_h


void warp3_init(int n1_in, float o1, float d1,
		int n2_in, float o2, float d2,
		int n3_in, float o3, float d3 /* output grid */,
		int nt, int ny_in, int nx_in  /* input  grid */,
		float eps                     /* regularization */);
/*< initialize >*/


void warp3_close(void);
/*< free allocated storage >*/


void warp3(float ***slice  /* [nx][ny][nt] input */,
	   float ***coord1 /* [nx][ny][nt] coordinates */,
	   float ***coord2 /* [nx][ny][nt] coordinates */,
	   float ***coord3 /* [nx][ny][nt] coordinates */,
	   float ***slice2 /* [n3][n2][n1] output */);
/*< apply warping >*/


void fwarp3(float ***slice2 /* [n3][n2][n1] input */,
	    float ***coord1 /* [nx][ny][nt] coordinates */,
	    float ***coord2 /* [nx][ny][nt] coordinates */,
	    float ***coord3 /* [nx][ny][nt] coordinates */,
	    float ***slice  /* [nx][ny][nt] output */);
/*< apply forward warping >*/

#endif
