/* This file is automatically generated. DO NOT EDIT! */

#ifndef _zoeppritz_h
#define _zoeppritz_h


void zoeppritz (int icoef /* (1, 2, 3) 
			     1: particle displacement
			     2: displacement potential
			     3: energy
			  */,
		float vp1, float vp2, 
		float vs1, float vs2, 
		float rho1, float rho2 /* P and S velocities and densitities */, 
		bool incp /* true if incident P wave, false if S wave */,
		float theta /* incident ray parameter */,
		float *rc  /* [4] reflection and transmission coefficients */,
		float *ang /* [4] phase rotation angle in radians */);
/*< reflection coefficients from Zoeppritz equation >*/

#endif
