/* This file is automatically generated. DO NOT EDIT! */

#ifndef _zomva_h
#define _zomva_h


#include <rsf.h>


void zomva_init(bool verb_,
		float eps_,
		bool twoway_,
		float dtmax,
		sf_axis aw_      /* frequency */,
		sf_axis amx_     /* i-line (data/image) */,
		sf_axis amy_     /* x-line (data/image) */,
		sf_axis amz_     /* depth */,
		sf_axis alx_     /* i-line (slowness) */,
		sf_axis aly_     /* x-line (slowness) */,
		int tmx, int tmy /* taper size */,
		int pmx, int pmy /* padding in the k domain */,
		int nrmax        /* maximum number of references */,
		sf_fslice slow_,
		sf_fslice wfld_);
/*< initialize >*/


void zomva_close(void);
/*< free allocated storage >*/


void zomva(bool inv     /* forward/adjoint flag */, 
	   sf_fslice Pslow /* slowness perturbation [nz][nmy][nmx] */,
	   sf_fslice Pimag /*    image perturbation [nz][nmy][nmx] */);
/*< Apply forward/adjoint ZO MVA >*/

#endif
